const country = [
  {
    countryName: "Afghanistan",
    countryCode: "AF",
    currency: "Afghan Afghani",
    currencySymbol: "؋",
    currencyCode: "AFN",
    phoneCode: "+93",
  },
  {
    countryName: "Albania",
    countryCode: "AL",
    currency: "Albanian Lek",
    currencySymbol: "L",
    currencyCode: "ALL",
    phoneCode: "+355",
  },
  {
    countryName: "Algeria",
    countryCode: "DZ",
    currency: "Algerian Dinar",
    currencySymbol: "د.ج",
    currencyCode: "DZD",
    phoneCode: "+213",
  },
  {
    countryName: "Andorra",
    countryCode: "AD",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+376",
  },
  {
    countryName: "Angola",
    countryCode: "AO",
    currency: "Angolan Kwanza",
    currencySymbol: "Kz",
    currencyCode: "AOA",
    phoneCode: "+244",
  },
  {
    countryName: "Antigua and Barbuda",
    countryCode: "AG",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
    phoneCode: "+1-268",
  },
  {
    countryName: "Argentina",
    countryCode: "AR",
    currency: "Argentine Peso",
    currencySymbol: "$",
    currencyCode: "ARS",
    phoneCode: "+54",
  },
  {
    countryName: "Armenia",
    countryCode: "AM",
    currency: "Armenian Dram",
    currencySymbol: "֏",
    currencyCode: "AMD",
    phoneCode: "+374",
  },
  {
    countryName: "Australia",
    countryCode: "AU",
    currency: "Australian Dollar",
    currencySymbol: "$",
    currencyCode: "AUD",
    phoneCode: "+61",
  },
  {
    countryName: "Austria",
    countryCode: "AT",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+43",
  },
  {
    countryName: "Azerbaijan",
    countryCode: "AZ",
    currency: "Azerbaijani Manat",
    currencySymbol: "₼",
    currencyCode: "AZN",
    phoneCode: "+994",
  },
  {
    countryName: "Bahamas",
    countryCode: "BS",
    currency: "Bahamian Dollar",
    currencySymbol: "$",
    currencyCode: "BSD",
    phoneCode: "+1-242",
  },
  {
    countryName: "Bahrain",
    countryCode: "BH",
    currency: "Bahraini Dinar",
    currencySymbol: ".د.ب",
    currencyCode: "BHD",
    phoneCode: "+973",
  },
  {
    countryName: "Bangladesh",
    countryCode: "BD",
    currency: "Bangladeshi Taka",
    currencySymbol: "৳",
    currencyCode: "BDT",
    phoneCode: "+880",
  },
  {
    countryName: "Barbados",
    countryCode: "BB",
    currency: "Barbadian Dollar",
    currencySymbol: "$",
    currencyCode: "BBD",
    phoneCode: "+1-246",
  },
  {
    countryName: "Belarus",
    countryCode: "BY",
    currency: "Belarusian Ruble",
    currencySymbol: "Br",
    currencyCode: "BYN",
    phoneCode: "+375",
  },
  {
    countryName: "Belgium",
    countryCode: "BE",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+32",
  },
  {
    countryName: "Belize",
    countryCode: "BZ",
    currency: "Belize Dollar",
    currencySymbol: "$",
    currencyCode: "BZD",
    phoneCode: "+501",
  },
  {
    countryName: "Benin",
    countryCode: "BJ",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
    phoneCode: "+229",
  },
  {
    countryName: "Bhutan",
    countryCode: "BT",
    currency: "Bhutanese Ngultrum",
    currencySymbol: "Nu.",
    currencyCode: "BTN",
    phoneCode: "+975",
  },
  {
    countryName: "Bolivia",
    countryCode: "BO",
    currency: "Bolivian Boliviano",
    currencySymbol: "Bs.",
    currencyCode: "BOB",
    phoneCode: "+591",
  },
  {
    countryName: "Bosnia and Herzegovina",
    countryCode: "BA",
    currency: "Convertible Mark",
    currencySymbol: "KM",
    currencyCode: "BAM",
    phoneCode: "+387",
  },
  {
    countryName: "Botswana",
    countryCode: "BW",
    currency: "Botswana Pula",
    currencySymbol: "P",
    currencyCode: "BWP",
    phoneCode: "+267",
  },
  {
    countryName: "Brazil",
    countryCode: "BR",
    currency: "Brazilian Real",
    currencySymbol: "R$",
    currencyCode: "BRL",
    phoneCode: "+55",
  },
  {
    countryName: "Brunei",
    countryCode: "BN",
    currency: "Brunei Dollar",
    currencySymbol: "$",
    currencyCode: "BND",
    phoneCode: "+673",
  },
  {
    countryName: "Bulgaria",
    countryCode: "BG",
    currency: "Bulgarian Lev",
    currencySymbol: "лв",
    currencyCode: "BGN",
    phoneCode: "+359",
  },

  {
    countryName: "Burkina Faso",
    countryCode: "BF",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
    phoneCode: "+226",
  },
  {
    countryName: "Burundi",
    countryCode: "BI",
    currency: "Burundian Franc",
    currencySymbol: "FBu",
    currencyCode: "BIF",
    phoneCode: "+257",
  },
  {
    countryName: "Cabo Verde",
    countryCode: "CV",
    currency: "Cape Verdean Escudo",
    currencySymbol: "$",
    currencyCode: "CVE",
    phoneCode: "+238",
  },
  {
    countryName: "Cambodia",
    countryCode: "KH",
    currency: "Cambodian Riel",
    currencySymbol: "៛",
    currencyCode: "KHR",
    phoneCode: "+855",
  },
  {
    countryName: "Cameroon",
    countryCode: "CM",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
    phoneCode: "+237",
  },
  {
    countryName: "Canada",
    countryCode: "CA",
    currency: "Canadian Dollar",
    currencySymbol: "$",
    currencyCode: "CAD",
    phoneCode: "+1",
  },
  {
    countryName: "Central African Republic",
    countryCode: "CF",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
    phoneCode: "+236",
  },
  {
    countryName: "Chad",
    countryCode: "TD",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
    phoneCode: "+235",
  },
  {
    countryName: "Chile",
    countryCode: "CL",
    currency: "Chilean Peso",
    currencySymbol: "$",
    currencyCode: "CLP",
    phoneCode: "+56",
  },
  {
    countryName: "China",
    countryCode: "CN",
    currency: "Chinese Yuan Renminbi",
    currencySymbol: "¥",
    currencyCode: "CNY",
    phoneCode: "+86",
  },
  {
    countryName: "Colombia",
    countryCode: "CO",
    currency: "Colombian Peso",
    currencySymbol: "$",
    currencyCode: "COP",
    phoneCode: "+57",
  },
  {
    countryName: "Comoros",
    countryCode: "KM",
    currency: "Comorian Franc",
    currencySymbol: "CF",
    currencyCode: "KMF",
    phoneCode: "+269",
  },
  {
    countryName: "Congo, Democratic Republic of the",
    countryCode: "CD",
    currency: "Congolese Franc",
    currencySymbol: "FC",
    currencyCode: "CDF",
    phoneCode: "+243",
  },
  {
    countryName: "Congo, Republic of the",
    countryCode: "CG",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
    phoneCode: "+242",
  },
  {
    countryName: "Costa Rica",
    countryCode: "CR",
    currency: "Costa Rican Colon",
    currencySymbol: "₡",
    currencyCode: "CRC",
    phoneCode: "+506",
  },
  {
    countryName: "Côte d’Ivoire",
    countryCode: "CI",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
    phoneCode: "+225",
  },
  {
    countryName: "Croatia",
    countryCode: "HR",
    currency: "Croatian Kuna",
    currencySymbol: "kn",
    currencyCode: "HRK",
    phoneCode: "+385",
  },
  {
    countryName: "Cuba",
    countryCode: "CU",
    currency: "Cuban Peso",
    currencySymbol: "$",
    currencyCode: "CUP",
    phoneCode: "+53",
  },
  {
    countryName: "Cyprus",
    countryCode: "CY",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+357",
  },
  {
    countryName: "Czech Republic",
    countryCode: "CZ",
    currency: "Czech Koruna",
    currencySymbol: "Kč",
    currencyCode: "CZK",
    phoneCode: "+420",
  },
  {
    countryName: "Denmark",
    countryCode: "DK",
    currency: "Danish Krone",
    currencySymbol: "kr",
    currencyCode: "DKK",
    phoneCode: "+45",
  },
  {
    countryName: "Djibouti",
    countryCode: "DJ",
    currency: "Djiboutian Franc",
    currencySymbol: "Fdj",
    currencyCode: "DJF",
    phoneCode: "+253",
  },
  {
    countryName: "Dominica",
    countryCode: "DM",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
    phoneCode: "+1-767",
  },
  {
    countryName: "Dominican Republic",
    countryCode: "DO",
    currency: "Dominican Peso",
    currencySymbol: "RD$",
    currencyCode: "DOP",
    phoneCode: "+1-809",
  },
  {
    countryName: "East Timor (Timor-Leste)",
    countryCode: "TL",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
    phoneCode: "+670",
  },
  {
    countryName: "Ecuador",
    countryCode: "EC",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
    phoneCode: "+593",
  },
  {
    countryName: "Egypt",
    countryCode: "EG",
    currency: "Egyptian Pound",
    currencySymbol: "E£",
    currencyCode: "EGP",
    phoneCode: "+20",
  },
  {
    countryName: "El Salvador",
    countryCode: "SV",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
    phoneCode: "+503",
  },
  {
    countryName: "Equatorial Guinea",
    countryCode: "GQ",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
    phoneCode: "+240",
  },
  {
    countryName: "Eritrea",
    countryCode: "ER",
    currency: "Eritrean Nakfa",
    currencySymbol: "Nfk",
    currencyCode: "ERN",
    phoneCode: "+291",
  },
  {
    countryName: "Estonia",
    countryCode: "EE",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+372",
  },
  {
    countryName: "Eswatini",
    countryCode: "SZ",
    currency: "Swazi Lilangeni",
    currencySymbol: "L",
    currencyCode: "SZL",
    phoneCode: "+268",
  },
  {
    countryName: "Ethiopia",
    countryCode: "ET",
    currency: "Ethiopian Birr",
    currencySymbol: "Br",
    currencyCode: "ETB",
    phoneCode: "+251",
  },
  {
    countryName: "Fiji",
    countryCode: "FJ",
    currency: "Fijian Dollar",
    currencySymbol: "$",
    currencyCode: "FJD",
    phoneCode: "+679",
  },

  {
    countryName: "Finland",
    countryCode: "FI",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+358",
  },
  {
    countryName: "France",
    countryCode: "FR",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+33",
  },
  {
    countryName: "Gabon",
    countryCode: "GA",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
    phoneCode: "+241",
  },
  {
    countryName: "The Gambia",
    countryCode: "GM",
    currency: "Gambian Dalasi",
    currencySymbol: "D",
    currencyCode: "GMD",
    phoneCode: "+220",
  },
  {
    countryName: "Georgia",
    countryCode: "GE",
    currency: "Georgian Lari",
    currencySymbol: "₾",
    currencyCode: "GEL",
    phoneCode: "+995",
  },
  {
    countryName: "Germany",
    countryCode: "DE",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+49",
  },
  {
    countryName: "Ghana",
    countryCode: "GH",
    currency: "Ghanaian Cedi",
    currencySymbol: "GH₵",
    currencyCode: "GHS",
    phoneCode: "+233",
  },
  {
    countryName: "Greece",
    countryCode: "GR",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+30",
  },
  {
    countryName: "Grenada",
    countryCode: "GD",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
    phoneCode: "+1-473",
  },
  {
    countryName: "Guatemala",
    countryCode: "GT",
    currency: "Guatemalan Quetzal",
    currencySymbol: "Q",
    currencyCode: "GTQ",
    phoneCode: "+502",
  },
  {
    countryName: "Guinea",
    countryCode: "GN",
    currency: "Guinean Franc",
    currencySymbol: "FG",
    currencyCode: "GNF",
    phoneCode: "+224",
  },
  {
    countryName: "Guinea-Bissau",
    countryCode: "GW",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
    phoneCode: "+245",
  },
  {
    countryName: "Guyana",
    countryCode: "GY",
    currency: "Guyanese Dollar",
    currencySymbol: "$",
    currencyCode: "GYD",
    phoneCode: "+592",
  },
  {
    countryName: "Haiti",
    countryCode: "HT",
    currency: "Haitian Gourde",
    currencySymbol: "G",
    currencyCode: "HTG",
    phoneCode: "+509",
  },
  {
    countryName: "Honduras",
    countryCode: "HN",
    currency: "Honduran Lempira",
    currencySymbol: "L",
    currencyCode: "HNL",
    phoneCode: "+504",
  },
  {
    countryName: "Hungary",
    countryCode: "HU",
    currency: "Hungarian Forint",
    currencySymbol: "Ft",
    currencyCode: "HUF",
    phoneCode: "+36",
  },
  {
    countryName: "Iceland",
    countryCode: "IS",
    currency: "Icelandic Króna",
    currencySymbol: "kr",
    currencyCode: "ISK",
    phoneCode: "+354",
  },
  {
    countryName: "India",
    countryCode: "IN",
    currency: "Indian Rupee",
    currencySymbol: "₹",
    currencyCode: "INR",
    phoneCode: "+91",
  },
  {
    countryName: "Indonesia",
    countryCode: "ID",
    currency: "Indonesian Rupiah",
    currencySymbol: "Rp",
    currencyCode: "IDR",
    phoneCode: "+62",
  },
  {
    countryName: "Iran",
    countryCode: "IR",
    currency: "Iranian Rial",
    currencySymbol: "﷼",
    currencyCode: "IRR",
    phoneCode: "+98",
  },
  {
    countryName: "Iraq",
    countryCode: "IQ",
    currency: "Iraqi Dinar",
    currencySymbol: "ع.د",
    currencyCode: "IQD",
    phoneCode: "+964",
  },
  {
    countryName: "Ireland",
    countryCode: "IE",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+353",
  },
  {
    countryName: "Israel",
    countryCode: "IL",
    currency: "Israeli New Shekel",
    currencySymbol: "₪",
    currencyCode: "ILS",
    phoneCode: "+972",
  },
  {
    countryName: "Italy",
    countryCode: "IT",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+39",
  },
  {
    countryName: "Jamaica",
    countryCode: "JM",
    currency: "Jamaican Dollar",
    currencySymbol: "$",
    currencyCode: "JMD",
    phoneCode: "+1-876",
  },
  {
    countryName: "Japan",
    countryCode: "JP",
    currency: "Japanese Yen",
    currencySymbol: "¥",
    currencyCode: "JPY",
    phoneCode: "+81",
  },
  {
    countryName: "Jordan",
    countryCode: "JO",
    currency: "Jordanian Dinar",
    currencySymbol: "د.ا",
    currencyCode: "JOD",
    phoneCode: "+962",
  },
  {
    countryName: "Kazakhstan",
    countryCode: "KZ",
    currency: "Kazakhstani Tenge",
    currencySymbol: "₸",
    currencyCode: "KZT",
    phoneCode: "+7",
  },
  {
    countryName: "Kenya",
    countryCode: "KE",
    currency: "Kenyan Shilling",
    currencySymbol: "KSh",
    currencyCode: "KES",
    phoneCode: "+254",
  },
  {
    countryName: "Kiribati",
    countryCode: "KI",
    currency: "Australian Dollar",
    currencySymbol: "$",
    currencyCode: "AUD",
    phoneCode: "+686",
  },
  {
    countryName: "Korea, North",
    countryCode: "KP",
    currency: "North Korean Won",
    currencySymbol: "₩",
    currencyCode: "KPW",
    phoneCode: "+850",
  },
  {
    countryName: "Korea, South",
    countryCode: "KR",
    currency: "South Korean Won",
    currencySymbol: "₩",
    currencyCode: "KRW",
    phoneCode: "+82",
  },
  {
    countryName: "Kosovo",
    countryCode: "XK",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+383",
  },
  {
    countryName: "Kuwait",
    countryCode: "KW",
    currency: "Kuwaiti Dinar",
    currencySymbol: "د.ك",
    currencyCode: "KWD",
    phoneCode: "+965",
  },
  {
    countryName: "Kyrgyzstan",
    countryCode: "KG",
    currency: "Kyrgyzstani Som",
    currencySymbol: "сом",
    currencyCode: "KGS",
    phoneCode: "+996",
  },
  {
    countryName: "Laos",
    countryCode: "LA",
    currency: "Lao Kip",
    currencySymbol: "₭",
    currencyCode: "LAK",
    phoneCode: "+856",
  },
  {
    countryName: "Latvia",
    countryCode: "LV",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+371",
  },
  {
    countryName: "Lebanon",
    countryCode: "LB",
    currency: "Lebanese Pound",
    currencySymbol: "ل.ل",
    currencyCode: "LBP",
    phoneCode: "+961",
  },
  {
    countryName: "Lesotho",
    countryCode: "LS",
    currency: "Lesotho Loti",
    currencySymbol: "L",
    currencyCode: "LSL",
    phoneCode: "+266",
  },
  {
    countryName: "Liberia",
    countryCode: "LR",
    currency: "Liberian Dollar",
    currencySymbol: "$",
    currencyCode: "LRD",
    phoneCode: "+231",
  },
  {
    countryName: "Libya",
    countryCode: "LY",
    currency: "Libyan Dinar",
    currencySymbol: "ل.د",
    currencyCode: "LYD",
    phoneCode: "+218",
  },
  {
    countryName: "Liechtenstein",
    countryCode: "LI",
    currency: "Swiss Franc",
    currencySymbol: "CHF",
    currencyCode: "CHF",
    phoneCode: "+423",
  },
  {
    countryName: "Lithuania",
    countryCode: "LT",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+370",
  },
  {
    countryName: "Luxembourg",
    countryCode: "LU",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+352",
  },
  {
    countryName: "Madagascar",
    countryCode: "MG",
    currency: "Malagasy Ariary",
    currencySymbol: "Ar",
    currencyCode: "MGA",
    phoneCode: "+261",
  },
  {
    countryName: "Malawi",
    countryCode: "MW",
    currency: "Malawian Kwacha",
    currencySymbol: "MK",
    currencyCode: "MWK",
    phoneCode: "+265",
  },
  {
    countryName: "Malaysia",
    countryCode: "MY",
    currency: "Malaysian Ringgit",
    currencySymbol: "RM",
    currencyCode: "MYR",
    phoneCode: "+60",
  },
  {
    countryName: "Maldives",
    countryCode: "MV",
    currency: "Maldivian Rufiyaa",
    currencySymbol: "Rf",
    currencyCode: "MVR",
    phoneCode: "+960",
  },
  {
    countryName: "Mali",
    countryCode: "ML",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
    phoneCode: "+223",
  },
  {
    countryName: "Malta",
    countryCode: "MT",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+356",
  },
  {
    countryName: "Marshall Islands",
    countryCode: "MH",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
    phoneCode: "+692",
  },
  {
    countryName: "Mauritania",
    countryCode: "MR",
    currency: "Mauritanian Ouguiya",
    currencySymbol: "UM",
    currencyCode: "MRU",
    phoneCode: "+222",
  },
  {
    countryName: "Mauritius",
    countryCode: "MU",
    currency: "Mauritian Rupee",
    currencySymbol: "₨",
    currencyCode: "MUR",
    phoneCode: "+230",
  },
  {
    countryName: "Mexico",
    countryCode: "MX",
    currency: "Mexican Peso",
    currencySymbol: "$",
    currencyCode: "MXN",
    phoneCode: "+52",
  },
  {
    countryName: "Micronesia, Federated States of",
    countryCode: "FM",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
    phoneCode: "+691",
  },
  {
    countryName: "Moldova",
    countryCode: "MD",
    currency: "Moldovan Leu",
    currencySymbol: "MDL",
    currencyCode: "MDL",
    phoneCode: "+373",
  },
  {
    countryName: "Monaco",
    countryCode: "MC",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+377",
  },
  {
    countryName: "Mongolia",
    countryCode: "MN",
    currency: "Mongolian Tugrik",
    currencySymbol: "₮",
    currencyCode: "MNT",
    phoneCode: "+976",
  },
  {
    countryName: "Montenegro",
    countryCode: "ME",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+382",
  },
  {
    countryName: "Morocco",
    countryCode: "MA",
    currency: "Moroccan Dirham",
    currencySymbol: "د.م.",
    currencyCode: "MAD",
    phoneCode: "+212",
  },
  {
    countryName: "Mozambique",
    countryCode: "MZ",
    currency: "Mozambican Metical",
    currencySymbol: "MT",
    currencyCode: "MZN",
    phoneCode: "+258",
  },

  {
    countryName: "Myanmar (Burma)",
    countryCode: "MM",
    currency: "Myanmar Kyat",
    currencySymbol: "Ks",
    currencyCode: "MMK",
    phoneCode: "+95",
  },
  {
    countryName: "Namibia",
    countryCode: "NA",
    currency: "Namibian Dollar",
    currencySymbol: "$",
    currencyCode: "NAD",
    phoneCode: "+264",
  },
  {
    countryName: "Nauru",
    countryCode: "NR",
    currency: "Australian Dollar",
    currencySymbol: "$",
    currencyCode: "AUD",
    phoneCode: "+674",
  },
  {
    countryName: "Nepal",
    countryCode: "NP",
    currency: "Nepalese Rupee",
    currencySymbol: "₨",
    currencyCode: "NPR",
    phoneCode: "+977",
  },
  {
    countryName: "Netherlands",
    countryCode: "NL",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+31",
  },
  {
    countryName: "New Zealand",
    countryCode: "NZ",
    currency: "New Zealand Dollar",
    currencySymbol: "$",
    currencyCode: "NZD",
    phoneCode: "+64",
  },
  {
    countryName: "Nicaragua",
    countryCode: "NI",
    currency: "Nicaraguan Córdoba",
    currencySymbol: "C$",
    currencyCode: "NIO",
    phoneCode: "+505",
  },
  {
    countryName: "Niger",
    countryCode: "NE",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
    phoneCode: "+227",
  },
  {
    countryName: "Nigeria",
    countryCode: "NG",
    currency: "Nigerian Naira",
    currencySymbol: "₦",
    currencyCode: "NGN",
    phoneCode: "+234",
  },
  {
    countryName: "North Macedonia",
    countryCode: "MK",
    currency: "Macedonian Denar",
    currencySymbol: "ден",
    currencyCode: "MKD",
    phoneCode: "+389",
  },
  {
    countryName: "Norway",
    countryCode: "NO",
    currency: "Norwegian Krone",
    currencySymbol: "kr",
    currencyCode: "NOK",
    phoneCode: "+47",
  },
  {
    countryName: "Oman",
    countryCode: "OM",
    currency: "Omani Rial",
    currencySymbol: "ر.ع.",
    currencyCode: "OMR",
    phoneCode: "+968",
  },
  {
    countryName: "Pakistan",
    countryCode: "PK",
    currency: "Pakistani Rupee",
    currencySymbol: "₨",
    currencyCode: "PKR",
    phoneCode: "+92",
  },
  {
    countryName: "Palau",
    countryCode: "PW",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
    phoneCode: "+680",
  },
  {
    countryName: "Panama",
    countryCode: "PA",
    currency: "Panamanian Balboa",
    currencySymbol: "B/.",
    currencyCode: "PAB",
    phoneCode: "+507",
  },
  {
    countryName: "Papua New Guinea",
    countryCode: "PG",
    currency: "Papua New Guinean Kina",
    currencySymbol: "K",
    currencyCode: "PGK",
    phoneCode: "+675",
  },
  {
    countryName: "Paraguay",
    countryCode: "PY",
    currency: "Paraguayan Guarani",
    currencySymbol: "₲",
    currencyCode: "PYG",
    phoneCode: "+595",
  },
  {
    countryName: "Peru",
    countryCode: "PE",
    currency: "Peruvian Sol",
    currencySymbol: "S/.",
    currencyCode: "PEN",
    phoneCode: "+51",
  },
  {
    countryName: "Philippines",
    countryCode: "PH",
    currency: "Philippine Peso",
    currencySymbol: "₱",
    currencyCode: "PHP",
    phoneCode: "+63",
  },
  {
    countryName: "Poland",
    countryCode: "PL",
    currency: "Polish Zloty",
    currencySymbol: "zł",
    currencyCode: "PLN",
    phoneCode: "+48",
  },
  {
    countryName: "Portugal",
    countryCode: "PT",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+351",
  },
  {
    countryName: "Qatar",
    countryCode: "QA",
    currency: "Qatari Riyal",
    currencySymbol: "ر.ق",
    currencyCode: "QAR",
    phoneCode: "+974",
  },
  {
    countryName: "Romania",
    countryCode: "RO",
    currency: "Romanian Leu",
    currencySymbol: "lei",
    currencyCode: "RON",
    phoneCode: "+40",
  },
  {
    countryName: "Russia",
    countryCode: "RU",
    currency: "Russian Ruble",
    currencySymbol: "₽",
    currencyCode: "RUB",
    phoneCode: "+7",
  },
  {
    countryName: "Rwanda",
    countryCode: "RW",
    currency: "Rwandan Franc",
    currencySymbol: "FRw",
    currencyCode: "RWF",
    phoneCode: "+250",
  },
  {
    countryName: "Saint Kitts and Nevis",
    countryCode: "KN",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
    phoneCode: "+1-869",
  },
  {
    countryName: "Saint Lucia",
    countryCode: "LC",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
    phoneCode: "+1-758",
  },
  {
    countryName: "Saint Vincent and the Grenadines",
    countryCode: "VC",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
    phoneCode: "+1-784",
  },
  {
    countryName: "Samoa",
    countryCode: "WS",
    currency: "Samoan Tala",
    currencySymbol: "T",
    currencyCode: "WST",
    phoneCode: "+685",
  },
  {
    countryName: "San Marino",
    countryCode: "SM",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+378",
  },
  {
    countryName: "Sao Tome and Principe",
    countryCode: "ST",
    currency: "São Tomé and Príncipe Dobra",
    currencySymbol: "Db",
    currencyCode: "STN",
    phoneCode: "+239",
  },
  {
    countryName: "Saudi Arabia",
    countryCode: "SA",
    currency: "Saudi Riyal",
    currencySymbol: "ر.س",
    currencyCode: "SAR",
    phoneCode: "+966",
  },
  {
    countryName: "Senegal",
    countryCode: "SN",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
    phoneCode: "+221",
  },
  {
    countryName: "Serbia",
    countryCode: "RS",
    currency: "Serbian Dinar",
    currencySymbol: "дин.",
    currencyCode: "RSD",
    phoneCode: "+381",
  },
  {
    countryName: "Seychelles",
    countryCode: "SC",
    currency: "Seychellois Rupee",
    currencySymbol: "₨",
    currencyCode: "SCR",
    phoneCode: "+248",
  },
  {
    countryName: "Sierra Leone",
    countryCode: "SL",
    currency: "Sierra Leonean Leone",
    currencySymbol: "Le",
    currencyCode: "SLL",
    phoneCode: "+232",
  },
  {
    countryName: "Singapore",
    countryCode: "SG",
    currency: "Singapore Dollar",
    currencySymbol: "$",
    currencyCode: "SGD",
    phoneCode: "+65",
  },
  {
    countryName: "Slovakia",
    countryCode: "SK",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+421",
  },
  {
    countryName: "Slovenia",
    countryCode: "SI",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+386",
  },
  {
    countryName: "Solomon Islands",
    countryCode: "SB",
    currency: "Solomon Islands Dollar",
    currencySymbol: "SI$",
    currencyCode: "SBD",
    phoneCode: "+677",
  },
  {
    countryName: "Somalia",
    countryCode: "SO",
    currency: "Somali Shilling",
    currencySymbol: "Sh",
    currencyCode: "SOS",
    phoneCode: "+252",
  },
  {
    countryName: "South Africa",
    countryCode: "ZA",
    currency: "South African Rand",
    currencySymbol: "R",
    currencyCode: "ZAR",
    phoneCode: "+27",
  },
  {
    countryName: "Spain",
    countryCode: "ES",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+34",
  },
  {
    countryName: "Sri Lanka",
    countryCode: "LK",
    currency: "Sri Lankan Rupee",
    currencySymbol: "රු",
    currencyCode: "LKR",
    phoneCode: "+94",
  },
  {
    countryName: "Sudan",
    countryCode: "SD",
    currency: "Sudanese Pound",
    currencySymbol: "ج.س.",
    currencyCode: "SDG",
    phoneCode: "+249",
  },
  {
    countryName: "South Sudan",
    countryCode: "SS",
    currency: "South Sudanese Pound",
    currencySymbol: "SSP",
    currencyCode: "SSP",
    phoneCode: "+211",
  },
  {
    countryName: "Suriname",
    countryCode: "SR",
    currency: "Surinamese Dollar",
    currencySymbol: "$",
    currencyCode: "SRD",
    phoneCode: "+597",
  },
  {
    countryName: "Sweden",
    countryCode: "SE",
    currency: "Swedish Krona",
    currencySymbol: "kr",
    currencyCode: "SEK",
    phoneCode: "+46",
  },
  {
    countryName: "Switzerland",
    countryCode: "CH",
    currency: "Swiss Franc",
    currencySymbol: "CHF",
    currencyCode: "CHF",
    phoneCode: "+41",
  },
  {
    countryName: "Syria",
    countryCode: "SY",
    currency: "Syrian Pound",
    currencySymbol: "£S",
    currencyCode: "SYP",
    phoneCode: "+963",
  },
  {
    countryName: "Taiwan",
    countryCode: "TW",
    currency: "New Taiwan Dollar",
    currencySymbol: "NT$",
    currencyCode: "TWD",
    phoneCode: "+886",
  },
  {
    countryName: "Tajikistan",
    countryCode: "TJ",
    currency: "Tajikistani Somoni",
    currencySymbol: "ЅМ",
    currencyCode: "TJS",
    phoneCode: "+992",
  },
  {
    countryName: "Tanzania",
    countryCode: "TZ",
    currency: "Tanzanian Shilling",
    currencySymbol: "TSh",
    currencyCode: "TZS",
    phoneCode: "+255",
  },
  {
    countryName: "Thailand",
    countryCode: "TH",
    currency: "Thai Baht",
    currencySymbol: "฿",
    currencyCode: "THB",
    phoneCode: "+66",
  },
  {
    countryName: "Togo",
    countryCode: "TG",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
    phoneCode: "+228",
  },
  {
    countryName: "Tonga",
    countryCode: "TO",
    currency: "Tongan Pa'anga",
    currencySymbol: "T$",
    currencyCode: "TOP",
    phoneCode: "+676",
  },
  {
    countryName: "Trinidad and Tobago",
    countryCode: "TT",
    currency: "Trinidad and Tobago Dollar",
    currencySymbol: "TT$",
    currencyCode: "TTD",
    phoneCode: "+1-868",
  },
  {
    countryName: "Tunisia",
    countryCode: "TN",
    currency: "Tunisian Dinar",
    currencySymbol: "د.ت",
    currencyCode: "TND",
    phoneCode: "+216",
  },
  {
    countryName: "Turkey",
    countryCode: "TR",
    currency: "Turkish Lira",
    currencySymbol: "₺",
    currencyCode: "TRY",
    phoneCode: "+90",
  },
  {
    countryName: "Turkmenistan",
    countryCode: "TM",
    currency: "Turkmenistan Manat",
    currencySymbol: "TMT",
    currencyCode: "TMT",
    phoneCode: "+993",
  },
  {
    countryName: "Tuvalu",
    countryCode: "TV",
    currency: "Australian Dollar",
    currencySymbol: "$",
    currencyCode: "AUD",
    phoneCode: "+688",
  },
  {
    countryName: "Uganda",
    countryCode: "UG",
    currency: "Ugandan Shilling",
    currencySymbol: "USh",
    currencyCode: "UGX",
    phoneCode: "+256",
  },
  {
    countryName: "Ukraine",
    countryCode: "UA",
    currency: "Ukrainian Hryvnia",
    currencySymbol: "₴",
    currencyCode: "UAH",
    phoneCode: "+380",
  },
  {
    countryName: "United Arab Emirates",
    countryCode: "AE",
    currency: "United Arab Emirates Dirham",
    currencySymbol: "د.إ",
    currencyCode: "AED",
    phoneCode: "+971",
  },
  {
    countryName: "United Kingdom",
    countryCode: "GB",
    currency: "British Pound Sterling",
    currencySymbol: "£",
    currencyCode: "GBP",
    phoneCode: "+44",
  },
  {
    countryName: "United States",
    countryCode: "US",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
    phoneCode: "+1",
  },
  {
    countryName: "Uruguay",
    countryCode: "UY",
    currency: "Uruguayan Peso",
    currencySymbol: "$",
    currencyCode: "UYU",
    phoneCode: "+598",
  },
  {
    countryName: "Uzbekistan",
    countryCode: "UZ",
    currency: "Uzbekistan Som",
    currencySymbol: "so'm",
    currencyCode: "UZS",
    phoneCode: "+998",
  },
  {
    countryName: "Vanuatu",
    countryCode: "VU",
    currency: "Vanuatu Vatu",
    currencySymbol: "VT",
    currencyCode: "VUV",
    phoneCode: "+678",
  },
  {
    countryName: "Vatican City",
    countryCode: "VA",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
    phoneCode: "+379",
  },
  {
    countryName: "Venezuela",
    countryCode: "VE",
    currency: "Venezuelan Bolívar",
    currencySymbol: "Bs.S.",
    currencyCode: "VES",
    phoneCode: "+58",
  },
  {
    countryName: "Vietnam",
    countryCode: "VN",
    currency: "Vietnamese Dong",
    currencySymbol: "₫",
    currencyCode: "VND",
    phoneCode: "+84",
  },
  {
    countryName: "Yemen",
    countryCode: "YE",
    currency: "Yemeni Rial",
    currencySymbol: "﷼",
    currencyCode: "YER",
    phoneCode: "+967",
  },
  {
    countryName: "Zambia",
    countryCode: "ZM",
    currency: "Zambian Kwacha",
    currencySymbol: "ZK",
    currencyCode: "ZMW",
    phoneCode: "+260",
  },
  {
    countryName: "Zimbabwe",
    countryCode: "ZW",
    currency: "Zimbabwean Dollar",
    currencySymbol: "$",
    currencyCode: "ZWL",
    phoneCode: "+263",
  },
];
const getCountry = () => {
  try {
    return country;
  } catch (error) {
    console.log(error);
  }
};

module.exports = { getCountry };
