const country = [
  {
    countryName: "Afghanistan",
    countryCode: "AF",
    currency: "Afghan Afghani",
    currencySymbol: "؋",
    currencyCode: "AFN",
  },

  {
    countryName: "Albania",
    countryCode: "AL",
    currency: "Albanian Lek",
    currencySymbol: "L",
    currencyCode: "ALL",
  },
  {
    countryName: "Algeria",
    countryCode: "DZ",
    currency: "Algerian Dinar",
    currencySymbol: "د.ج",
    currencyCode: "DZD",
  },

  {
    countryName: "Andorra",
    countryCode: "AD",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Angola",
    countryCode: "AO",
    currency: "Angolan Kwanza",
    currencySymbol: "Kz",
    currencyCode: "AOA",
  },
  {
    countryName: "Antigua and Barbuda",
    countryCode: "AG",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
  },
  {
    countryName: "Argentina",
    countryCode: "AR",
    currency: "Argentine Peso",
    currencySymbol: "$",
    currencyCode: "ARS",
  },
  {
    countryName: "Armenia",
    countryCode: "AM",
    currency: "Armenian Dram",
    currencySymbol: "֏",
    currencyCode: "AMD",
  },

  {
    countryName: "Australia",
    countryCode: "AU",
    currency: "Australian Dollar",
    currencySymbol: "$",
    currencyCode: "AUD",
  },

  {
    countryName: "Austria",
    countryCode: "AT",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },

  {
    countryName: "Azerbaijan",
    countryCode: "AZ",
    currency: "Azerbaijani Manat",
    currencySymbol: "₼",
    currencyCode: "AZN",
  },

  {
    countryName: "The Bahamas",
    countryCode: "BS",
    currency: "Bahamian Dollar",
    currencySymbol: "$",
    currencyCode: "BSD",
  },

  {
    countryName: "Bahrain",
    countryCode: "BH",
    currency: "Bahraini Dinar",
    currencySymbol: "BD",
    currencyCode: "BHD",
  },

  {
    countryName: "Bangladesh",
    countryCode: "BD",
    currency: "Bangladeshi Taka",
    currencySymbol: "৳",
    currencyCode: "BDT",
  },

  {
    countryName: "Barbados",
    countryCode: "BB",
    currency: "Barbadian Dollar",
    currencySymbol: "$",
    currencyCode: "BBD",
  },

  {
    countryName: "Belarus",
    countryCode: "BY",
    currency: "Belarusian Ruble",
    currencySymbol: "Br",
    currencyCode: "BYN",
  },

  {
    countryName: "Belgium",
    countryCode: "BE",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },

  {
    countryName: "Belize",
    countryCode: "BZ",
    currency: "Belize Dollar",
    currencySymbol: "$",
    currencyCode: "BZD",
  },

  {
    countryName: "Benin",
    countryCode: "BJ",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
  },

  {
    countryName: "Bhutan",
    countryCode: "BT",
    currency: "Bhutanese Ngultrum",
    currencySymbol: "Nu.",
    currencyCode: "BTN",
  },

  {
    countryName: "Bolivia",
    countryCode: "BO",
    currency: "Bolivian Boliviano",
    currencySymbol: "Bs.",
    currencyCode: "BOB",
  },

  {
    countryName: "Bosnia and Herzegovina",
    countryCode: "BA",
    currency: "Bosnia and Herzegovina Convertible Mark",
    currencySymbol: "KM",
    currencyCode: "BAM",
  },

  {
    countryName: "Botswana",
    countryCode: "BW",
    currency: "Botswana Pula",
    currencySymbol: "P",
    currencyCode: "BWP",
  },

  {
    countryName: "Brazil",
    countryCode: "BR",
    currency: "Brazilian Real",
    currencySymbol: "R$",
    currencyCode: "BRL",
  },

  {
    countryName: "Brunei",
    countryCode: "BN",
    currency: "Brunei Dollar",
    currencySymbol: "$",
    currencyCode: "BND",
  },

  {
    countryName: "Bulgaria",
    countryCode: "BG",
    currency: "Bulgarian Lev",
    currencySymbol: "лв",
    currencyCode: "BGN",
  },

  {
    countryName: "Burkina Faso",
    countryCode: "BF",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
  },

  {
    countryName: "Burundi",
    countryCode: "BI",
    currency: "Burundian Franc",
    currencySymbol: "FBu",
    currencyCode: "BIF",
  },

  {
    countryName: "Cabo Verde",
    countryCode: "CV",
    currency: "Cape Verdean Escudo",
    currencySymbol: "$",
    currencyCode: "CVE",
  },

  {
    countryName: "Cambodia",
    countryCode: "KH",
    currency: "Cambodian Riel",
    currencySymbol: "៛",
    currencyCode: "KHR",
  },

  {
    countryName: "Cameroon",
    countryCode: "CM",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
  },

  {
    countryName: "Canada",
    countryCode: "CA",
    currency: "Canadian Dollar",
    currencySymbol: "$",
    currencyCode: "CAD",
  },

  {
    countryName: "Central African Republic",
    countryCode: "CF",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
  },

  {
    countryName: "Chad",
    countryCode: "TD",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
  },

  {
    countryName: "Chile",
    countryCode: "CL",
    currency: "Chilean Peso",
    currencySymbol: "$",
    currencyCode: "CLP",
  },

  {
    countryName: "China",
    countryCode: "CN",
    currency: "Chinese Yuan Renminbi",
    currencySymbol: "¥",
    currencyCode: "CNY",
  },

  {
    countryName: "Colombia",
    countryCode: "CO",
    currency: "Colombian Peso",
    currencySymbol: "$",
    currencyCode: "COP",
  },

  {
    countryName: "Comoros",
    countryCode: "KM",
    currency: "Comorian Franc",
    currencySymbol: "CF",
    currencyCode: "KMF",
  },

  {
    countryName: "Congo, Democratic Republic of the",
    countryCode: "CD",
    currency: "Congolese Franc",
    currencySymbol: "FC",
    currencyCode: "CDF",
  },

  {
    countryName: "Congo, Republic of the",
    countryCode: "CG",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
  },

  {
    countryName: "Costa Rica",
    countryCode: "CR",
    currency: "Costa Rican Colon",
    currencySymbol: "₡",
    currencyCode: "CRC",
  },

  {
    countryName: "Côte d’Ivoire",
    countryCode: "CI",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
  },

  {
    countryName: "Croatia",
    countryCode: "HR",
    currency: "Croatian Kuna",
    currencySymbol: "kn",
    currencyCode: "HRK",
  },

  {
    countryName: "Cuba",
    countryCode: "CU",
    currency: "Cuban Peso",
    currencySymbol: "$",
    currencyCode: "CUP",
  },

  {
    countryName: "Cyprus",
    countryCode: "CY",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },

  {
    countryName: "Czech Republic",
    countryCode: "CZ",
    currency: "Czech Koruna",
    currencySymbol: "Kč",
    currencyCode: "CZK",
  },

  {
    countryName: "Denmark",
    countryCode: "DK",
    currency: "Danish Krone",
    currencySymbol: "kr",
    currencyCode: "DKK",
  },

  {
    countryName: "Djibouti",
    countryCode: "DJ",
    currency: "Djiboutian Franc",
    currencySymbol: "Fdj",
    currencyCode: "DJF",
  },

  {
    countryName: "Dominica",
    countryCode: "DM",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
  },

  {
    countryName: "Dominican Republic",
    countryCode: "DO",
    currency: "Dominican Peso",
    currencySymbol: "RD$",
    currencyCode: "DOP",
  },

  {
    countryName: "East Timor (Timor-Leste)",
    countryCode: "TL",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
  },

  {
    countryName: "Ecuador",
    countryCode: "EC",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
  },

  {
    countryName: "Egypt",
    countryCode: "EG",
    currency: "Egyptian Pound",
    currencySymbol: "E£",
    currencyCode: "EGP",
  },

  {
    countryName: "El Salvador",
    countryCode: "SV",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
  },

  {
    countryName: "Equatorial Guinea",
    countryCode: "GQ",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
  },

  {
    countryName: "Eritrea",
    countryCode: "ER",
    currency: "Eritrean Nakfa",
    currencySymbol: "Nfk",
    currencyCode: "ERN",
  },

  {
    countryName: "Estonia",
    countryCode: "EE",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },

  {
    countryName: "Eswatini",
    countryCode: "SZ",
    currency: "Swazi Lilangeni",
    currencySymbol: "L",
    currencyCode: "SZL",
  },

  {
    countryName: "Ethiopia",
    countryCode: "ET",
    currency: "Ethiopian Birr",
    currencySymbol: "Br",
    currencyCode: "ETB",
  },

  {
    countryName: "Fiji",
    countryCode: "FJ",
    currency: "Fijian Dollar",
    currencySymbol: "$",
    currencyCode: "FJD",
  },

  {
    countryName: "Finland",
    countryCode: "FI",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },

  {
    countryName: "France",
    countryCode: "FR",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },

  {
    countryName: "Gabon",
    countryCode: "GA",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XAF",
  },
  {
    countryName: "The Gambia",
    countryCode: "GM",
    currency: "Gambian Dalasi",
    currencySymbol: "D",
    currencyCode: "GMD",
  },
  {
    countryName: "Georgia",
    countryCode: "GE",
    currency: "Georgian Lari",
    currencySymbol: "₾",
    currencyCode: "GEL",
  },
  {
    countryName: "Germany",
    countryCode: "DE",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Ghana",
    countryCode: "GH",
    currency: "Ghanaian Cedi",
    currencySymbol: "GH₵",
    currencyCode: "GHS",
  },
  {
    countryName: "Greece",
    countryCode: "GR",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Grenada",
    countryCode: "GD",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
  },
  {
    countryName: "Guatemala",
    countryCode: "GT",
    currency: "Guatemalan Quetzal",
    currencySymbol: "Q",
    currencyCode: "GTQ",
  },
  {
    countryName: "Guinea",
    countryCode: "GN",
    currency: "Guinean Franc",
    currencySymbol: "FG",
    currencyCode: "GNF",
  },
  {
    countryName: "Guinea-Bissau",
    countryCode: "GW",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
  },
  {
    countryName: "Guyana",
    countryCode: "GY",
    currency: "Guyanese Dollar",
    currencySymbol: "$",
    currencyCode: "GYD",
  },

  {
    countryName: "Haiti",
    countryCode: "HT",
    currency: "Haitian Gourde",
    currencySymbol: "G",
    currencyCode: "HTG",
  },
  {
    countryName: "Honduras",
    countryCode: "HN",
    currency: "Honduran Lempira",
    currencySymbol: "L",
    currencyCode: "HNL",
  },
  {
    countryName: "Hungary",
    countryCode: "HU",
    currency: "Hungarian Forint",
    currencySymbol: "Ft",
    currencyCode: "HUF",
  },

  {
    countryName: "Iceland",
    countryCode: "IS",
    currency: "Icelandic Króna",
    currencySymbol: "kr",
    currencyCode: "ISK",
  },
  {
    countryName: "India",
    countryCode: "IN",
    currency: "Indian Rupee",
    currencySymbol: "₹",
    currencyCode: "INR",
  },
  {
    countryName: "Indonesia",
    countryCode: "ID",
    currency: "Indonesian Rupiah",
    currencySymbol: "Rp",
    currencyCode: "IDR",
  },
  {
    countryName: "Iran",
    countryCode: "IR",
    currency: "Iranian Rial",
    currencySymbol: "﷼",
    currencyCode: "IRR",
  },
  {
    countryName: "Iraq",
    countryCode: "IQ",
    currency: "Iraqi Dinar",
    currencySymbol: "ع.د",
    currencyCode: "IQD",
  },
  {
    countryName: "Ireland",
    countryCode: "IE",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Israel",
    countryCode: "IL",
    currency: "Israeli New Shekel",
    currencySymbol: "₪",
    currencyCode: "ILS",
  },
  {
    countryName: "Italy",
    countryCode: "IT",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Jamaica",
    countryCode: "JM",
    currency: "Jamaican Dollar",
    currencySymbol: "$",
    currencyCode: "JMD",
  },
  {
    countryName: "Japan",
    countryCode: "JP",
    currency: "Japanese Yen",
    currencySymbol: "¥",
    currencyCode: "JPY",
  },
  {
    countryName: "Jordan",
    countryCode: "JO",
    currency: "Jordanian Dinar",
    currencySymbol: "د.ا",
    currencyCode: "JOD",
  },

  {
    countryName: "Kazakhstan",
    countryCode: "KZ",
    currency: "Kazakhstani Tenge",
    currencySymbol: "₸",
    currencyCode: "KZT",
  },
  {
    countryName: "Kenya",
    countryCode: "KE",
    currency: "Kenyan Shilling",
    currencySymbol: "KSh",
    currencyCode: "KES",
  },
  {
    countryName: "Kiribati",
    countryCode: "KI",
    currency: "Australian Dollar",
    currencySymbol: "$",
    currencyCode: "AUD",
  },
  {
    countryName: "Korea, North",
    countryCode: "KP",
    currency: "North Korean Won",
    currencySymbol: "₩",
    currencyCode: "KPW",
  },
  {
    countryName: "Korea, South",
    countryCode: "KR",
    currency: "South Korean Won",
    currencySymbol: "₩",
    currencyCode: "KRW",
  },
  {
    countryName: "Kosovo",
    countryCode: "XK",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Kuwait",
    countryCode: "KW",
    currency: "Kuwaiti Dinar",
    currencySymbol: "د.ك",
    currencyCode: "KWD",
  },
  {
    countryName: "Kyrgyzstan",
    countryCode: "KG",
    currency: "Kyrgyzstani Som",
    currencySymbol: "сом",
    currencyCode: "KGS",
  },

  {
    countryName: "Laos",
    countryCode: "LA",
    currency: "Lao Kip",
    currencySymbol: "₭",
    currencyCode: "LAK",
  },
  {
    countryName: "Latvia",
    countryCode: "LV",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Lebanon",
    countryCode: "LB",
    currency: "Lebanese Pound",
    currencySymbol: "ل.ل",
    currencyCode: "LBP",
  },
  {
    countryName: "Lesotho",
    countryCode: "LS",
    currency: "Lesotho Loti",
    currencySymbol: "L",
    currencyCode: "LSL",
  },
  {
    countryName: "Liberia",
    countryCode: "LR",
    currency: "Liberian Dollar",
    currencySymbol: "$",
    currencyCode: "LRD",
  },
  {
    countryName: "Libya",
    countryCode: "LY",
    currency: "Libyan Dinar",
    currencySymbol: "ل.د",
    currencyCode: "LYD",
  },
  {
    countryName: "Liechtenstein",
    countryCode: "LI",
    currency: "Swiss Franc",
    currencySymbol: "CHF",
    currencyCode: "CHF",
  },

  {
    countryName: "Lithuania",
    countryCode: "LT",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Luxembourg",
    countryCode: "LU",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },

  {
    countryName: "Madagascar",
    countryCode: "MG",
    currency: "Malagasy Ariary",
    currencySymbol: "Ar",
    currencyCode: "MGA",
  },
  {
    countryName: "Malawi",
    countryCode: "MW",
    currency: "Malawian Kwacha",
    currencySymbol: "MK",
    currencyCode: "MWK",
  },
  {
    countryName: "Malaysia",
    countryCode: "MY",
    currency: "Malaysian Ringgit",
    currencySymbol: "RM",
    currencyCode: "MYR",
  },
  {
    countryName: "Maldives",
    countryCode: "MV",
    currency: "Maldivian Rufiyaa",
    currencySymbol: "Rf",
    currencyCode: "MVR",
  },
  {
    countryName: "Mali",
    countryCode: "ML",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
  },
  {
    countryName: "Malta",
    countryCode: "MT",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Marshall Islands",
    countryCode: "MH",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
  },
  {
    countryName: "Mauritania",
    countryCode: "MR",
    currency: "Mauritanian Ouguiya",
    currencySymbol: "UM",
    currencyCode: "MRU",
  },

  {
    countryName: "Mauritius",
    countryCode: "MU",
    currency: "Mauritian Rupee",
    currencySymbol: "₨",
    currencyCode: "MUR",
  },
  {
    countryName: "Mexico",
    countryCode: "MX",
    currency: "Mexican Peso",
    currencySymbol: "$",
    currencyCode: "MXN",
  },
  {
    countryName: "Micronesia, Federated States of",
    countryCode: "FM",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
  },
  {
    countryName: "Moldova",
    countryCode: "MD",
    currency: "Moldovan Leu",
    currencySymbol: "MDL",
    currencyCode: "MDL",
  },
  {
    countryName: "Monaco",
    countryCode: "MC",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Mongolia",
    countryCode: "MN",
    currency: "Mongolian Tugrik",
    currencySymbol: "₮",
    currencyCode: "MNT",
  },

  {
    countryName: "Montenegro",
    countryCode: "ME",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Morocco",
    countryCode: "MA",
    currency: "Moroccan Dirham",
    currencySymbol: "د.م.",
    currencyCode: "MAD",
  },
  {
    countryName: "Mozambique",
    countryCode: "MZ",
    currency: "Mozambican Metical",
    currencySymbol: "MT",
    currencyCode: "MZN",
  },
  {
    countryName: "Myanmar (Burma)",
    countryCode: "MM",
    currency: "Myanmar Kyat",
    currencySymbol: "Ks",
    currencyCode: "MMK",
  },

  {
    countryName: "Namibia",
    countryCode: "NA",
    currency: "Namibian Dollar",
    currencySymbol: "$",
    currencyCode: "NAD",
  },
  {
    countryName: "Nauru",
    countryCode: "NR",
    currency: "Australian Dollar",
    currencySymbol: "$",
    currencyCode: "AUD",
  },
  {
    countryName: "Nepal",
    countryCode: "NP",
    currency: "Nepalese Rupee",
    currencySymbol: "₨",
    currencyCode: "NPR",
  },
  {
    countryName: "Netherlands",
    countryCode: "NL",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "New Zealand",
    countryCode: "NZ",
    currency: "New Zealand Dollar",
    currencySymbol: "$",
    currencyCode: "NZD",
  },
  {
    countryName: "Nicaragua",
    countryCode: "NI",
    currency: "Nicaraguan Córdoba",
    currencySymbol: "C$",
    currencyCode: "NIO",
  },
  {
    countryName: "Niger",
    countryCode: "NE",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
  },
  {
    countryName: "Nigeria",
    countryCode: "NG",
    currency: "Nigerian Naira",
    currencySymbol: "₦",
    currencyCode: "NGN",
  },
  {
    countryName: "North Macedonia",
    countryCode: "MK",
    currency: "Macedonian Denar",
    currencySymbol: "ден",
    currencyCode: "MKD",
  },
  {
    countryName: "Norway",
    countryCode: "NO",
    currency: "Norwegian Krone",
    currencySymbol: "kr",
    currencyCode: "NOK",
  },

  {
    countryName: "Oman",
    countryCode: "OM",
    currency: "Omani Rial",
    currencySymbol: "ر.ع.",
    currencyCode: "OMR",
  },

  {
    countryName: "Pakistan",
    countryCode: "PK",
    currency: "Pakistani Rupee",
    currencySymbol: "₨",
    currencyCode: "PKR",
  },
  {
    countryName: "Palau",
    countryCode: "PW",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
  },
  {
    countryName: "Panama",
    countryCode: "PA",
    currency: "Panamanian Balboa",
    currencySymbol: "B/.",
    currencyCode: "PAB",
  },
  {
    countryName: "Papua New Guinea",
    countryCode: "PG",
    currency: "Papua New Guinean Kina",
    currencySymbol: "K",
    currencyCode: "PGK",
  },
  {
    countryName: "Paraguay",
    countryCode: "PY",
    currency: "Paraguayan Guarani",
    currencySymbol: "₲",
    currencyCode: "PYG",
  },
  {
    countryName: "Peru",
    countryCode: "PE",
    currency: "Peruvian Sol",
    currencySymbol: "S/.",
    currencyCode: "PEN",
  },
  {
    countryName: "Philippines",
    countryCode: "PH",
    currency: "Philippine Peso",
    currencySymbol: "₱",
    currencyCode: "PHP",
  },
  {
    countryName: "Poland",
    countryCode: "PL",
    currency: "Polish Zloty",
    currencySymbol: "zł",
    currencyCode: "PLN",
  },
  {
    countryName: "Portugal",
    countryCode: "PT",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },

  {
    countryName: "Qatar",
    countryCode: "QA",
    currency: "Qatari Riyal",
    currencySymbol: "ر.ق",
    currencyCode: "QAR",
  },

  {
    countryName: "Romania",
    countryCode: "RO",
    currency: "Romanian Leu",
    currencySymbol: "lei",
    currencyCode: "RON",
  },
  {
    countryName: "Russia",
    countryCode: "RU",
    currency: "Russian Ruble",
    currencySymbol: "₽",
    currencyCode: "RUB",
  },
  {
    countryName: "Rwanda",
    countryCode: "RW",
    currency: "Rwandan Franc",
    currencySymbol: "FRw",
    currencyCode: "RWF",
  },

  {
    countryName: "Saint Kitts and Nevis",
    countryCode: "KN",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
  },
  {
    countryName: "Saint Lucia",
    countryCode: "LC",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
  },
  {
    countryName: "Saint Vincent and the Grenadines",
    countryCode: "VC",
    currency: "East Caribbean Dollar",
    currencySymbol: "$",
    currencyCode: "XCD",
  },
  {
    countryName: "Samoa",
    countryCode: "WS",
    currency: "Samoan Tala",
    currencySymbol: "T",
    currencyCode: "WST",
  },
  {
    countryName: "San Marino",
    countryCode: "SM",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Sao Tome and Principe",
    countryCode: "ST",
    currency: "São Tomé and Príncipe Dobra",
    currencySymbol: "Db",
    currencyCode: "STN",
  },
  {
    countryName: "Saudi Arabia",
    countryCode: "SA",
    currency: "Saudi Riyal",
    currencySymbol: "ر.س",
    currencyCode: "SAR",
  },
  {
    countryName: "Senegal",
    countryCode: "SN",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
  },

  {
    countryName: "Serbia",
    countryCode: "RS",
    currency: "Serbian Dinar",
    currencySymbol: "дин.",
    currencyCode: "RSD",
  },
  {
    countryName: "Seychelles",
    countryCode: "SC",
    currency: "Seychellois Rupee",
    currencySymbol: "₨",
    currencyCode: "SCR",
  },
  {
    countryName: "Sierra Leone",
    countryCode: "SL",
    currency: "Sierra Leonean Leone",
    currencySymbol: "Le",
    currencyCode: "SLL",
  },
  {
    countryName: "Singapore",
    countryCode: "SG",
    currency: "Singapore Dollar",
    currencySymbol: "$",
    currencyCode: "SGD",
  },
  {
    countryName: "Slovakia",
    countryCode: "SK",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Slovenia",
    countryCode: "SI",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Solomon Islands",
    countryCode: "SB",
    currency: "Solomon Islands Dollar",
    currencySymbol: "SI$",
    currencyCode: "SBD",
  },
  {
    countryName: "Somalia",
    countryCode: "SO",
    currency: "Somali Shilling",
    currencySymbol: "Sh",
    currencyCode: "SOS",
  },

  {
    countryName: "South Africa",
    countryCode: "ZA",
    currency: "South African Rand",
    currencySymbol: "R",
    currencyCode: "ZAR",
  },
  {
    countryName: "Spain",
    countryCode: "ES",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Sri Lanka",
    countryCode: "LK",
    currency: "Sri Lankan Rupee",
    currencySymbol: "රු",
    currencyCode: "LKR",
  },
  {
    countryName: "Sudan",
    countryCode: "SD",
    currency: "Sudanese Pound",
    currencySymbol: "ج.س.",
    currencyCode: "SDG",
  },
  {
    countryName: "South Sudan",
    countryCode: "SS",
    currency: "South Sudanese Pound",
    currencySymbol: "SSP",
    currencyCode: "SSP",
  },
  {
    countryName: "Suriname",
    countryCode: "SR",
    currency: "Surinamese Dollar",
    currencySymbol: "$",
    currencyCode: "SRD",
  },
  {
    countryName: "Sweden",
    countryCode: "SE",
    currency: "Swedish Krona",
    currencySymbol: "kr",
    currencyCode: "SEK",
  },
  {
    countryName: "Switzerland",
    countryCode: "CH",
    currency: "Swiss Franc",
    currencySymbol: "CHF",
    currencyCode: "CHF",
  },
  {
    countryName: "Syria",
    countryCode: "SY",
    currency: "Syrian Pound",
    currencySymbol: "£S",
    currencyCode: "SYP",
  },

  {
    countryName: "Taiwan",
    countryCode: "TW",
    currency: "New Taiwan Dollar",
    currencySymbol: "NT$",
    currencyCode: "TWD",
  },
  {
    countryName: "Tajikistan",
    countryCode: "TJ",
    currency: "Tajikistani Somoni",
    currencySymbol: "ЅМ",
    currencyCode: "TJS",
  },
  {
    countryName: "Tanzania",
    countryCode: "TZ",
    currency: "Tanzanian Shilling",
    currencySymbol: "TSh",
    currencyCode: "TZS",
  },
  {
    countryName: "Thailand",
    countryCode: "TH",
    currency: "Thai Baht",
    currencySymbol: "฿",
    currencyCode: "THB",
  },

  {
    countryName: "Togo",
    countryCode: "TG",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
    currencyCode: "XOF",
  },
  {
    countryName: "Tonga",
    countryCode: "TO",
    currency: "Tongan Pa'anga",
    currencySymbol: "T$",
    currencyCode: "TOP",
  },
  {
    countryName: "Trinidad and Tobago",
    countryCode: "TT",
    currency: "Trinidad and Tobago Dollar",
    currencySymbol: "TT$",
    currencyCode: "TTD",
  },
  {
    countryName: "Tunisia",
    countryCode: "TN",
    currency: "Tunisian Dinar",
    currencySymbol: "د.ت",
    currencyCode: "TND",
  },

  {
    countryName: "Turkey",
    countryCode: "TR",
    currency: "Turkish Lira",
    currencySymbol: "₺",
    currencyCode: "TRY",
  },
  {
    countryName: "Turkmenistan",
    countryCode: "TM",
    currency: "Turkmenistan Manat",
    currencySymbol: "TMT",
    currencyCode: "TMT",
  },
  {
    countryName: "Tuvalu",
    countryCode: "TV",
    currency: "Australian Dollar",
    currencySymbol: "$",
    currencyCode: "AUD",
  },

  {
    countryName: "Uganda",
    countryCode: "UG",
    currency: "Ugandan Shilling",
    currencySymbol: "USh",
    currencyCode: "UGX",
  },
  {
    countryName: "Ukraine",
    countryCode: "UA",
    currency: "Ukrainian Hryvnia",
    currencySymbol: "₴",
    currencyCode: "UAH",
  },
  {
    countryName: "United Arab Emirates",
    countryCode: "AE",
    currency: "United Arab Emirates Dirham",
    currencySymbol: "د.إ",
    currencyCode: "AED",
  },
  {
    countryName: "United Kingdom",
    countryCode: "GB",
    currency: "British Pound Sterling",
    currencySymbol: "£",
    currencyCode: "GBP",
  },
  {
    countryName: "United States",
    countryCode: "US",
    currency: "United States Dollar",
    currencySymbol: "$",
    currencyCode: "USD",
  },
  {
    countryName: "Uruguay",
    countryCode: "UY",
    currency: "Uruguayan Peso",
    currencySymbol: "$",
    currencyCode: "UYU",
  },
  {
    countryName: "Uzbekistan",
    countryCode: "UZ",
    currency: "Uzbekistan Som",
    currencySymbol: "so'm",
    currencyCode: "UZS",
  },

  {
    countryName: "Vanuatu",
    countryCode: "VU",
    currency: "Vanuatu Vatu",
    currencySymbol: "VT",
    currencyCode: "VUV",
  },
  {
    countryName: "Vatican City",
    countryCode: "VA",
    currency: "Euro",
    currencySymbol: "€",
    currencyCode: "EUR",
  },
  {
    countryName: "Venezuela",
    countryCode: "VE",
    currency: "Venezuelan Bolívar",
    currencySymbol: "Bs.S.",
    currencyCode: "VES",
  },
  {
    countryName: "Vietnam",
    countryCode: "VN",
    currency: "Vietnamese Dong",
    currencySymbol: "₫",
    currencyCode: "VND",
  },

  {
    countryName: "Yemen",
    countryCode: "YE",
    currency: "Yemeni Rial",
    currencySymbol: "﷼",
    currencyCode: "YER",
  },
  {
    countryName: "Zambia",
    countryCode: "ZM",
    currency: "Zambian Kwacha",
    currencySymbol: "ZK",
    currencyCode: "ZMW",
  },
  {
    countryName: "Zimbabwe",
    countryCode: "ZW",
    currency: "Zimbabwean Dollar",
    currencySymbol: "$",
    currencyCode: "ZWL",
  },
];
const getCountry = () => {
  try {
    return country;
  } catch (error) {
    console.log(error);
  }
};
module.exports = {getCountry};
