name:"publish"

on:
    push:
        branches:
              -develop

jobs:
    release:
          name: publish
          runs-on : ubuntu-latest
          steps:
              -name: checkout
              uses: action/checkout@v2.1.1
              -name: node
              uses: actions/setup-node@v1.4.2
              with:
                  node-version:20
                  registry-url: https://registry.npmjs.org
              - name:publish
                run: npm publish --access public
                env: NPM_SECRET: ${{environments.NPM_SECRET}}