name: publish

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
