name: Publish Package to npmjs

on:
  push:
    branches:
      - develop  # This will trigger the workflow on pushes to the 'develop' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js and npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
        
      # Install dependencies
      - run: npm ci

      # Publish the package to npm
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
